name: password_manager
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter

  #  local DB objectbox (based on sqlite)
  objectbox: ^2.4.0
  objectbox_flutter_libs: any
  path_provider: ^2.0.10
  path: ^1.8.0
  json_annotation: ^4.8.1

  fluttertoast: ^8.2.4

  #  add customized splash screen & launcher icon
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1

  #  to add most of all validations
  validators: ^3.0.0

  #  shared prefs
  shared_preferences: ^2.2.2

  # auto size text view
  auto_size_text: ^3.0.0

#  flutter profile picture
  flutter_profile_picture: ^2.0.0

#  multi formatter
  flutter_multi_formatter: ^2.12.4

#  encrypt
  encrypt: ^5.0.3

#  auth
  local_auth: ^2.2.0

dev_dependencies:
  analyzer: ^6.4.1
  flutter_lints: 3.0.2
  build_runner: ^2.4.8
  objectbox_generator: ^2.4.0
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

flutter:
#  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

get_cli:
  sub_folder: false

objectbox:
  # Writes objectbox-model.json and objectbox.g.dart to lib/custom (and test/custom).
  output_dir: generated/objectBox

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/pm_logo.png"
  color_dark: "#121212"
  image_dark: "assets/images/pm_logo.png"

  android_12:
    image: "assets/images/pm_logo.png"
    icon_background_color: "#ffffff"
    image_dark: "assets/images/pm_logo.png"
    icon_background_color_dark: "#353535"

  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/pm_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/pm_logo.png"
    background_color: "#353535"
    theme_color: "#353535"
  windows:
    generate: true
    image_path: "assets/images/pm_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/pm_logo.png"
